force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Enter the email to use for communications sent to the Attendee related to the Event.</description>
    <inlineHelpText>Enter the email to use for communications sent to the Attendee related to the Event.</inlineHelpText>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Event.</description>
    <inlineHelpText>** Required ** Link to Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AttendeeService.cls
@IsTest
private class Test_AttendeeService {
    
    @isTest
    static void testcreateAttendee() {
        RestRequest req = new RestRequest();
        System.RestResponse res = new System.RestResponse();
        
        Event__c evt = new Event__c();
        evt.Name = 'TestEvent';
        insert evt;
        
        List<AttendeeService.EventAttendee> evtAtt = new List<AttendeeService.EventAttendee>();
        AttendeeService.EventAttendee att = new AttendeeService.EventAttendee();
        att.firstName = 'test1';
        att.lastName = 'test1';
        att.email = 'test1@xyz.com';
        att.eventId = evt.Id;
        evtAtt.add(att);
        
        req.requestURI = '/services/apexrest/AttendeeService';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(evtAtt));
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        AttendeeService.createAttendee();
        Test.stopTest();

        System.assertNotEquals(null, res.responseBody.toString());
        
        Attendee__c createdatt = [Select Id From Attendee__c Where Email__c = 'test1@xyz.com' Limit 1];
        System.assertNotEquals(null, createdatt.Id);
    }
}