force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <description>Attendees track individuals registered for Events.</description>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Enter the email to use for communications sent to the Attendee related to the Event.</description>
    <inlineHelpText>Enter the email to use for communications sent to the Attendee related to the Event.</inlineHelpText>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Event.</description>
    <inlineHelpText>** Required ** Link to Event.</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Defines the first name of the attendee</description>
    <inlineHelpText>Defines the first name of the attendee</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Defines the last name of the attendee</description>
    <inlineHelpText>Defines the last name of the attendee</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>The date the Attendee registered for the Event.</description>
    <inlineHelpText>The date the Attendee registered for the Event.</inlineHelpText>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</description>
    <inlineHelpText>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeService.cls
@RestResource(urlMapping='/AttendeeService/*')
global class AttendeeService {

    public class EventAttendee {
        public String firstName;
        public String lastName;
        public String email;
        public String eventId;
    }

    @HttpPost
    global static void createAttendee() {
        RestUtils.setupRequest();
        EventAttendee[] evntatt = (EventAttendee[]) JSON.deserialize(RestUtils.getBody(),List<EventAttendee>.class);
        List<Attendee__c> attendees = new List<Attendee__c>();
        try {  
            for(EventAttendee att : evntatt){
            if(att.eventId == null){
                RestResponse responseObj = new RestResponse();
                responseObj.addError('Missing Required Query Parameter eventId');
                responseObj.generateResponse();
            }
            else{
                Attendee__c attd = new Attendee__c();
                attd.First_Name__c = att.firstname;
                attd.Last_Name__c = att.lastname;
                attd.Email__c = att.email;
                attd.Event__c = att.eventId;
                attd.Status__c = 'Registered';
                attd.Registration_Date__c = System.today();
                attendees.add(attd);
            }   
        }
        insert attendees;   
        RestResponse responseObj = new RestResponse(attendees);
        responseObj.generateResponse();  
   } catch (Exception e) {
       RestResponse responseObj = new RestResponse();
       responseObj.addError(e.getMessage() + e.getStackTraceString());
       responseObj.generateResponse();
   }          
}
    
}