force-app/main/default/objects/Bonus__c/Bonus__c.object-meta.xml
<CustomObject>
    <description>Entry for Bonus</description>
    <label>Bonus</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bonus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The bonus end date.</description>
    <inlineHelpText>The bonus end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus__c/fields/Is_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the payouts has been processed with the batch</description>
    <inlineHelpText>When checked, the payouts has been processed with the batch</inlineHelpText>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bonus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The bonus start date.</description>
    <inlineHelpText>The bonus start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus_Payouts__c/Bonus_Payouts__c.object-meta.xml
<CustomObject>
    <description>Entry for Bonus Payouts</description>
    <label>Bonus_Payouts</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bonus Payout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus_Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus_Payouts__c/fields/Bonus__c.field-meta.xml
<CustomField>
    <fullName>Bonus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Bonus.</description>
    <inlineHelpText>** Required ** Link to Bonus.</inlineHelpText>
    <label>Bonus</label>
    <referenceTo>Bonus__c</referenceTo>
    <relationshipLabel>BonusPayouts</relationshipLabel>
    <relationshipName>Bonus_BonusPayouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_BonusBatchable.cls
@isTest 
public class Test_BonusBatchable 
{
    static testMethod void testMethod1() 
    {

        List<Bonus__c> lstbonus= new List<Bonus__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Bonus__c bon = new Bonus__c();
            bon.Start_Date__c = System.today();
            bon.End_Date__c = System.today().addMonths(2);
            lstbonus.add(bon);
        }
        
        insert lstbonus;
        
        Test.startTest();
            BonusBatchable obj = new BonusBatchable();
            DataBase.executeBatch(obj); 
         Test.stopTest();

         Set<Id> bonSet = new Set<Id>();
            for(Bonus__c bon : lstbonus){
                bonSet.add(bon.Id);
            }

         List<Bonus_Payouts__c> pays = [SELECT Id, Bonus__r.Is_Processed__c FROM Bonus_Payouts__c WHERE Bonus__c IN : bonSet];
            for(Bonus_Payouts__c bp : pays){
           System.assertEquals(true, bp.Bonus__r.Is_Processed__c);
        }
        System.assertEquals(600, pays.size());
        
    }
}