force-app/main/default/objects/Bonus__c/Bonus__c.object-meta.xml
<CustomObject>
    <description>Entry for Bonus</description>
    <label>Bonus</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bonus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The bonus end date.</description>
    <inlineHelpText>The bonus end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus__c/fields/Is_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, the payouts has been processed with the batch</description>
    <inlineHelpText>When checked, the payouts has been processed with the batch</inlineHelpText>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bonus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The bonus start date.</description>
    <inlineHelpText>The bonus start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus_Payouts__c/Bonus_Payouts__c.object-meta.xml
<CustomObject>
    <description>Entry for Bonus Payouts</description>
    <label>Bonus_Payouts</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bonus Payout ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus_Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus_Payouts__c/fields/Bonus__c.field-meta.xml
<CustomField>
    <fullName>Bonus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>** Required ** Link to Bonus.</description>
    <inlineHelpText>** Required ** Link to Bonus.</inlineHelpText>
    <label>Bonus</label>
    <referenceTo>Bonus__c</referenceTo>
    <relationshipLabel>BonusPayouts</relationshipLabel>
    <relationshipName>Bonus_BonusPayouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bonus_Payouts__c/fields/Payout_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_End_Date__c</fullName>
    <description>The bonus payout end date.</description>
    <inlineHelpText>The bonus payout end date</inlineHelpText>
    <label>Payout End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bonus_Payouts__c/fields/Payout_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Start_Date__c</fullName>
    <description>The bonus payout start date.</description>
    <inlineHelpText>The bonus payout start date</inlineHelpText>
    <label>Payout Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BonusBatchable.cls
public class BonusBatchable implements Database.Batchable<sObject>, Database.stateful {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query;

        query = 'Select Id, Start_Date__c, End_Date__c From Bonus__c Where Is_Processed__c = false ORDER BY Name ASC LIMIT 10000';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Bonus__c> scope) {

    try {
        List<Bonus_Payouts__c> payoutsDates = new List<Bonus_Payouts__c>();
        List<Bonus__c> updateProcessed = new List<Bonus__c>();

        for(Bonus__c bonus : scope){
            for(Integer i = 0 ; i < (bonus.Start_Date__c.monthsBetween(bonus.End_Date__c) + 1); i++){
                //month start and end date
                Bonus_Payouts__c pay = new Bonus_Payouts__c();
                pay.Payout_Start_Date__c = bonus.Start_Date__c.toStartofMonth().addMonths(i);
                pay.Payout_End_Date__c = bonus.Start_Date__c.addMonths(1+i).toStartofMonth().addDays(-1);
                pay.Bonus__c = bonus.Id;
                payoutsDates.add(pay);
            }
            if(!payoutsDates.isEmpty()){
            bonus.Is_Processed__c = true;
            updateProcessed.add(bonus);
            }
        }

    insert payoutsDates;

    if(!updateProcessed.isEmpty()){
    update updateProcessed; 
    }
    
}
    catch (Exception ex) {
        System.debug(ex);
    }
    }

    public void finish(Database.BatchableContext BC) {
      
    }

}