force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Events_Settings__c/Events_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Events_Settings</label>
</CustomObject>

force-app/main/default/objects/Events_Settings__c/fields/Max_Events_Limit__c.field-meta.xml
<CustomField>
    <fullName>Max_Events_Limit__c</fullName>
    <description>The maximum number of events per user.</description>
    <label>Max_Events_Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EventTriggerHandler.cls
public class EventTriggerHandler {
    public static void LimitNoOfEvents(List<Event__c> eventList) {
        Integer monthNumber = Date.Today().Month();
        Integer yearNumber = Date.Today().Year();

        //Custom setting config for events max limit
        Events_Settings__c eventSetting = [SELECT Id, Max_Events_Limit__c FROM Events_Settings__c LIMIT 1];
        Integer configEventMaxCount = (Integer.valueOf(eventSetting.Max_Events_Limit__c));
        List<Event__c> thisMonthEventList = [SELECT Id,CreatedById,CreatedDate FROM Event__c WHERE CALENDAR_YEAR(CreatedDate) =:YearNumber and CALENDAR_MONTH(CreatedDate)=:monthnumber and CreatedById=:UserInfo.GetUserId()];
        
        if (thisMonthEventList.Size()>=configEventMaxCount)         
            eventList[0].addError('Too many Events created this month for user ' + UserInfo.getName() +'('+ userinfo.getuserId()+'):' + thisMonthEventList.Size());
    }
}